//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_CreateProject_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_CreateProject_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\myhnz\AppData\Local\Temp\9B824F79FE451947EBA96B8B1A3F01CD8617\2\InternshipManagement\InternshipManagement\Views\Instructor\CreateProject.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\myhnz\AppData\Local\Temp\9B824F79FE451947EBA96B8B1A3F01CD8617\2\InternshipManagement\InternshipManagement\Views\Instructor\CreateProject.cshtml"
using (Html.BeginForm("CreateProject", "Instructor", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    

#line default
#line hidden

#line 3 "C:\Users\myhnz\AppData\Local\Temp\9B824F79FE451947EBA96B8B1A3F01CD8617\2\InternshipManagement\InternshipManagement\Views\Instructor\CreateProject.cshtml"
__o = Html.AntiForgeryToken();


#line default
#line hidden

#line 4 "C:\Users\myhnz\AppData\Local\Temp\9B824F79FE451947EBA96B8B1A3F01CD8617\2\InternshipManagement\InternshipManagement\Views\Instructor\CreateProject.cshtml"
                            

    

#line default
#line hidden

#line 5 "C:\Users\myhnz\AppData\Local\Temp\9B824F79FE451947EBA96B8B1A3F01CD8617\2\InternshipManagement\InternshipManagement\Views\Instructor\CreateProject.cshtm
   __o = Html.ValidationSummary(true, "", new { @class = "text-danger" });


#line default
#line hidden

#line 6 "C:\Users\myhnz\AppData\Local\Temp\9B824F79FE451947EBA96B8B1A3F01CD8617\2\InternshipManagement\InternshipManagement\Views\Instructor\CreateProject.cshtm       __o = Html.LabelFor(model => model.ProjectName, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 7 "C:\Users\myhnz\AppData\Local\Temp\9B824F79FE451947EBA96B8B1A3F01CD8617\2\InternshipManagement\InternshipManagement\Views\Instructor\CreateProject.cshtm           __o = Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 8 "C:\Users\myhnz\AppData\Local\Temp\9B824F79FE451947EBA96B8B1A3F01CD8617\2\InternshipManagement\InternshipManagement\Views\Instructor\CreateProject.cshtm           __o = Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" });


#line default
#line hidden

#line 9 "C:\Users\myhnz\AppData\Local\Temp\9B824F79FE451947EBA96B8B1A3F01CD8617\2\InternshipManagement\InternshipManagement\Views\Instructor\CreateProject.cshtm       __o = Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 10 "C:\Users\myhnz\AppData\Local\Temp\9B824F79FE451947EBA96B8B1A3F01CD8617\2\InternshipManagement\InternshipManagement\Views\Instructor\CreateProject.cshtm           __o = Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 11 "C:\Users\myhnz\AppData\Local\Temp\9B824F79FE451947EBA96B8B1A3F01CD8617\2\InternshipManagement\InternshipManagement\Views\Instructor\CreateProject.cshtm           __o = Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" });


#line default
#line hidden

#line 12 "C:\Users\myhnz\AppData\Local\Temp\9B824F79FE451947EBA96B8B1A3F01CD8617\2\InternshipManagement\InternshipManagement\Views\Instructor\CreateProject.cshtm       __o = Html.LabelFor(model => model.MaxStudents, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 13 "C:\Users\myhnz\AppData\Local\Temp\9B824F79FE451947EBA96B8B1A3F01CD8617\2\InternshipManagement\InternshipManagement\Views\Instructor\CreateProject.cshtm           __o = Html.EditorFor(model => model.MaxStudents, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 14 "C:\Users\myhnz\AppData\Local\Temp\9B824F79FE451947EBA96B8B1A3F01CD8617\2\InternshipManagement\InternshipManagement\Views\Instructor\CreateProject.cshtm           __o = Html.ValidationMessageFor(model => model.MaxStudents, "", new { @class = "text-danger" });


#line default
#line hidden

#line 15 "C:\Users\myhnz\AppData\Local\Temp\9B824F79FE451947EBA96B8B1A3F01CD8617\2\InternshipManagement\InternshipManagement\Views\Instructor\CreateProject.cshtm       __o = Html.Label("Tags", "Tags:", htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 16 "C:\Users\myhnz\AppData\Local\Temp\9B824F79FE451947EBA96B8B1A3F01CD8617\2\InternshipManagement\InternshipManagement\Views\Instructor\CreateProject.cshtm           __o = Html.ListBox("Tags", ViewBag.Tags as MultiSelectList, new { @class = "form-control", multiple = "multiple" });


#line default
#line hidden

#line 17 "C:\Users\myhnz\AppData\Local\Temp\9B824F79FE451947EBA96B8B1A3F01CD8617\2\InternshipManagement\InternshipManagement\Views\Instructor\CreateProject.cshtshipManagement\InternshipManagement\Views\Instruct18\CreateProject.cshtm          
}

#line default
#line hidden

#line 19 "C:\Users\myhnz\AppData\Local\Temp\9B824F79FE451947EBA96B8B1A3F01CD8617\2\InternshipManagement\InternshipManagement\Views\Instructor\CreateProject.cshtml"
__o = Html.ActionLink("Back to List", "Index");
19
#line default
#line hidden
DefineSection("scripts", () => {


#line 20 "C:\Users\my
#line 20 "C:\Users\myhnz\AppData\Local\Temp\9B824F79FE451947EBA96B8B1A3F01CD8617\2\InternshipManagement\InternshipManagement\Views\Instructor\CreateProject.20html"
                 __o = Url.Action(/YourCo
')          });


#line default
#
#line 21 "C:\Users\myhnz\AppData\Local\Temp\9B824F79FE451947EBA96B8B1A3F01CD8617\2\InternshipManagement\InternshipManagement\Views\Instructor\CreateProject.cshtml"
                 __o = Url.Action("AddTag");


#line default
#line hidden
line hidden
line default
#line hidden

#line default
#line hidden
ault
#line hidden


}
}
}
