//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternshipManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternshipInformation
    {
        public int InternshipID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> InstructorID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Description { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual Project Project { get; set; }
        public virtual Student Student { get; set; }
    }
}
