//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_CreateUserAccount_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_CreateUserAccount_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
  
    ViewBag.Title = "CreateUserAccount";


#line default
#line hidden

#line 3 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
using (Html.BeginForm("CreateUserAccount", "Admin", FormMethod.Post, new { @enctype = "multipart/form-data" })) 
{
    

#line default
#line hidden

#line 4 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
__o = Html.AntiForgeryToken();


#line default
#line hidden

#line 5 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
                            
    
    

#line default
#line hidden

#line 6 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
   __o = Html.ValidationSummary(true, "", new { @class = "text-danger" });


#line default
#line hidden

#line 7 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
       __o = Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 8 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
           __o = Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 9 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
           __o = Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" });


#line default
#line hidden

#line 10 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
       __o = Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 11 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
           __o = Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 12 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
           __o = Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" });


#line default
#line hidden

#line 13 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
       __o = Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 14 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
           __o = Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 15 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
           __o = Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" });


#line default
#line hidden

#line 16 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
       __o = Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 17 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
           __o = Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", type = "password"} });


#line default
#line hidden

#line 18 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
           __o = Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" });


#line default
#line hidden

#line 19 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
       __o = Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 20 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
           __o = Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control", type = "date" } });


#line default
#line hidden

#line 21 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
           __o = Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" });


#line default
#line hidden

#line 22 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
       __o = Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 23 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
           __o = Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 24 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
           __o = Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" });


#line default
#line hidden

#line 25 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
       __o = Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 26 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
           __o = Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 27 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
           __o = Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" });


#line default
#line hidden

#line 28 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
       __o = Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 29 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
           __o = Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 30 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
           __o = Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" });


#line default
#line hidden

#line 31 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
       __o = Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 32 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
           __o = Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 33 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
           __o = Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" });


#line default
#line hidden

#line 34 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
       __o = Html.LabelFor(model => model.RoleID) htmlAttributes: new { @class = "control-label col-md-2" }


#line default
#line hidden

#line 35 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
           __o = Html.DropDownList("RoleID", ViewBag.Roles as SelectList, "Chọn vai trò", new { @class = "form-control" } );


#line default
#line hidden

#line 36 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
           __o = Html.ValidationMessageFor(model => model.RoleID, "", new { @c
     "text-danger" });


#line default
#line hidden

#line 37 "C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
        
}

#line default
#line hidden

#line 3838C:\Users\binhh\AppData\Local\Temp\5288489FF7444D352ADCB8B03F5A2A947A6B\8\InternshipManagement\InternshipManagement\Views\Admin\CreateUserAccount.cshtml"
__o = Html.ActionLink("Back to List", "Index");


#line default
#line hidden
}
}
}
